'use client'

import { useState } from 'react'
import { AnimatePresence, motion } from 'motion/react'
import { Check, ChevronRight, Copy, GitBranch, Layers3, Moon, Package, Play, Sparkles, Zap } from 'lucide-react'
import { CodeBlock } from './code-block'

const modules = [
  { name: 'Core', detail: 'Lifecycle, themes & cleanup', icon: Layers3 },
  { name: 'Window', detail: 'Tabs, sections & layouts', icon: Package },
  { name: 'Controls', detail: 'Toggle, slider, dropdown & keybind', icon: Zap },
  { name: 'Motion', detail: 'Enter, spring & transitions', icon: Sparkles },
]
const installCode = `local Dereus = require(ReplicatedStorage.Packages.Dereus)
local ui = Dereus.new({ Name = "ControlCenter" })

local window = ui:CreateWindow({
  Title = "Control Center",
  Size = UDim2.fromOffset(640, 460),
})`

export function LibraryPage() {
  const [active, setActive] = useState('Core')
  const [copied, setCopied] = useState(false)
  const copy = async () => { await navigator.clipboard?.writeText(installCode); setCopied(true); setTimeout(() => setCopied(false), 1400) }
  return (
    <div className="relative min-h-screen overflow-hidden bg-background text-foreground">
      <div className="pointer-events-none absolute inset-0 grid-lines opacity-70" />
      <div className="pointer-events-none absolute left-1/2 top-[-18rem] h-[36rem] w-[56rem] -translate-x-1/2 rounded-full bg-primary/10 blur-[120px]" />
      <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-10">
        <a href="/" className="flex items-center gap-3 font-display text-lg font-bold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Moon className="size-4" /></span>Dereus Library</a>
        <nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#modules" className="transition-colors hover:text-foreground">Modules</a><a href="#docs" className="transition-colors hover:text-foreground">Docs</a><a href="https://github.com/donniehuamani-max/dereus-luau" target="_blank" rel="noreferrer" className="flex items-center gap-2 hover:text-foreground"><GitBranch className="size-4" /> GitHub</a></nav>
      </header>
      <main className="relative z-10 mx-auto max-w-7xl px-5 pb-24 lg:px-10">
        <section className="grid min-h-[70vh] items-center gap-14 py-20 lg:grid-cols-[1.05fr_.95fr] lg:py-28">
          <div><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="mb-7 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary"><span className="size-1.5 animate-pulse rounded-full bg-primary" /> Lua + Luau • v2.1.0</motion.div><motion.h1 initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }} className="max-w-3xl font-display text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-7xl">Build interfaces that feel <span className="text-primary text-glow">alive.</span></motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .18 }} className="mt-7 max-w-xl text-lg leading-8 text-muted-foreground">Dereus Library es una UI toolkit modular, portable y animation-first para Lua y Luau. Diseña herramientas, paneles y experiencias completas con una API coherente.</motion.p><div className="mt-9 flex flex-wrap gap-3"><a href="#docs" className="group inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground transition-transform hover:-translate-y-0.5">Empezar ahora <ChevronRight className="size-4 transition-transform group-hover:translate-x-1" /></a><a href="https://github.com/donniehuamani-max/dereus-luau" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-2xl border border-border bg-card/70 px-5 py-3 text-sm font-semibold transition-colors hover:bg-accent"><GitBranch className="size-4" /> Ver repositorio</a></div></div>
          <motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .15, type: 'spring', stiffness: 100 }} className="rounded-[2rem] border border-border bg-card/75 p-3 shadow-2xl shadow-primary/5 backdrop-blur-xl"><div className="overflow-hidden rounded-[1.5rem] border border-border bg-background"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div className="flex gap-1.5"><span className="size-2 rounded-full bg-destructive/80" /><span className="size-2 rounded-full bg-chart-3" /><span className="size-2 rounded-full bg-primary" /></div><span className="font-mono text-[10px] text-muted-foreground">dereus / preview</span></div><div className="grid min-h-[310px] grid-cols-[130px_1fr]"><div className="border-r border-border p-3"><div className="mb-4 px-2 text-[10px] font-bold uppercase tracking-[.2em] text-muted-foreground">Workspace</div>{['Overview','Components','Settings'].map((item, i) => <div key={item} className={`mb-1 rounded-xl px-3 py-2 text-xs ${i === 0 ? 'bg-primary/15 font-semibold text-primary' : 'text-muted-foreground'}`}>{item}</div>)}</div><div className="p-5"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">Good evening</p><h3 className="mt-1 font-display text-2xl font-semibold">Control center</h3></div><div className="grid size-9 place-items-center rounded-xl bg-primary/15 text-primary"><Play className="size-4" /></div></div><div className="grid grid-cols-2 gap-3">{['Smooth motion','Theme tokens','Safe cleanup','Typed API'].map((x, i) => <div key={x} className="rounded-2xl border border-border bg-card p-3"><div className="mb-5 size-7 rounded-lg bg-primary/10" /><p className="text-xs font-semibold">{x}</p><p className="mt-1 text-[10px] text-muted-foreground">Ready to use</p></div>)}</div></div></div></div></motion.div>
        </section>
        <section id="modules" className="border-t border-border py-20"><div className="mb-9 flex items-end justify-between gap-6"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-primary">The toolkit</p><h2 className="font-display text-4xl font-semibold tracking-[-.04em]">Todo lo que necesitas.</h2></div><p className="hidden max-w-sm text-sm leading-6 text-muted-foreground md:block">Una base sólida para interfaces profesionales sin repetir lógica ni pelearte con estados.</p></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{modules.map(({ name, detail, icon: Icon }, i) => <motion.button key={name} onClick={() => setActive(name)} whileHover={{ y: -5 }} className={`group rounded-3xl border p-5 text-left transition-colors ${active === name ? 'border-primary/50 bg-primary/10' : 'border-border bg-card/60 hover:bg-accent'}`}><div className={`mb-10 grid size-10 place-items-center rounded-2xl ${active === name ? 'bg-primary text-primary-foreground' : 'bg-accent text-muted-foreground'}`}><Icon className="size-5" /></div><h3 className="font-display text-lg font-semibold">{name}</h3><p className="mt-1 text-sm text-muted-foreground">{detail}</p><ChevronRight className="mt-5 size-4 text-primary opacity-0 transition-opacity group-hover:opacity-100" /></motion.button>)}</div></section>
        <section id="docs" className="grid gap-8 border-t border-border py-20 lg:grid-cols-[.7fr_1.3fr]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.2em] text-primary">Quick start</p><h2 className="font-display text-4xl font-semibold tracking-[-.04em]">Una API. Cualquier runtime.</h2><p className="mt-5 max-w-md leading-7 text-muted-foreground">Lua puro para tus herramientas y Luau nativo para Roblox Studio. Los módulos comparten la misma filosofía: composición, cleanup y motion predecible.</p><div className="mt-8 space-y-3">{['Lua 5.1 / 5.2 / 5.3', 'Luau + Roblox Studio', 'Sin dependencias externas', 'MIT License'].map((item) => <div key={item} className="flex items-center gap-3 text-sm"><span className="grid size-5 place-items-center rounded-full bg-primary/15 text-primary"><Check className="size-3" /></span>{item}</div>)}</div></div><div className="rounded-3xl border border-border bg-card/60 p-3"><div className="flex items-center justify-between px-4 py-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-primary" /> init.lua</div><button onClick={copy} className="flex items-center gap-1.5 text-xs text-muted-foreground transition-colors hover:text-primary">{copied ? <Check className="size-3.5 text-primary" /> : <Copy className="size-3.5" />}{copied ? 'Copied' : 'Copy'}</button></div><CodeBlock code={installCode} language="lua" /></div></section>
        <section className="rounded-[2rem] border border-primary/20 bg-primary/10 p-8 text-center sm:p-14"><Sparkles className="mx-auto size-7 text-primary" /><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-.04em]">Make your next interface feel like Dereus.</h2><p className="mx-auto mt-3 max-w-lg text-muted-foreground">La librería sigue creciendo. Explora el código, crea tus componentes y construye experiencias más expresivas.</p><a href="https://github.com/donniehuamani-max/dereus-luau" target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground"><GitBranch className="size-4" /> Abrir en GitHub</a></section>
      </main>
    </div>
  )
}
