"use client"

import { useState } from "react"
import { AnimatePresence, motion } from "motion/react"
import { ArrowRight, BookOpen, Check, ChevronRight, Clipboard, Code2, GitBranch, Layers3, Menu, Package, Sparkles, Terminal, X, Zap } from "lucide-react"

const modules = [
  { name: "Core", description: "Lifecycle, cleanup and predictable state for every host.", icon: Layers3, color: "text-primary" },
  { name: "Window", description: "Tabs, pages and responsive containers for Studio tools.", icon: Package, color: "text-sky-300" },
  { name: "Components", description: "Buttons, toggles, sliders, inputs and composed controls.", icon: Code2, color: "text-amber-300" },
  { name: "Motion", description: "Cinematic entrances, staggered reveals and spring transitions.", icon: Zap, color: "text-fuchsia-300" },
]

const docs = ["Overview", "Installation", "API surface", "Compatibility"]
const install = `local Dereus = require(ReplicatedStorage.Packages.DereusLibrary)
local ui = Dereus.new({ Name = "ControlCenter" })
local window = ui.Window.new(ui, { Title = "Control Center" })`

export function LibraryPage() {
  const [activeDoc, setActiveDoc] = useState("Overview")
  const [copied, setCopied] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const copy = async () => { await navigator.clipboard.writeText(install); setCopied(true); window.setTimeout(() => setCopied(false), 1400) }
  return <main className="min-h-screen overflow-hidden bg-[#0b0d12] text-white">
    <div className="pointer-events-none fixed inset-0 grid-lines opacity-40" />
    <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
      <a href="/library" className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><BookOpen className="size-4" /></span><span><b className="block text-sm">Dereus Library</b><small className="block text-[10px] uppercase tracking-[.22em] text-white/40">Lua + Luau toolkit</small></span></a>
      <nav className="hidden items-center gap-7 text-sm text-white/55 md:flex"><a href="#modules" className="hover:text-white">Modules</a><a href="#docs" className="hover:text-white">Docs</a><a href="https://github.com/donniehuamani-max/dereus-luau" target="_blank" rel="noreferrer" className="flex items-center gap-2 text-white hover:text-primary"><GitBranch className="size-4" /> GitHub</a></nav>
      <button className="rounded-xl border border-white/10 p-2 md:hidden" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle navigation">{mobileOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button>
    </header>
    <AnimatePresence>{mobileOpen && <motion.nav initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} className="relative z-20 mx-5 grid gap-1 rounded-2xl border border-white/10 bg-white/[.06] p-2 backdrop-blur-xl md:hidden"><a href="#modules" className="rounded-xl p-3 text-white/70">Modules</a><a href="#docs" className="rounded-xl p-3 text-white/70">Docs</a><a href="https://github.com/donniehuamani-max/dereus-luau" className="rounded-xl p-3 text-white/70">GitHub</a></motion.nav>}</AnimatePresence>
    <section className="relative mx-auto max-w-7xl px-5 pb-24 pt-20 lg:px-8 lg:pt-28"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }} className="max-w-4xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary"><Sparkles className="size-3.5" /> Dereus Library 2.8.0 <span className="text-white/35">·</span> Lua + Luau</div><h1 className="font-display text-5xl font-medium leading-[.98] tracking-[-.06em] sm:text-7xl lg:text-[6.5rem]">The expressive<br /><span className="text-primary text-glow">library layer.</span></h1><p className="mt-8 max-w-2xl text-base leading-7 text-white/55 sm:text-lg">Dereus Library es la librería independiente para construir interfaces, herramientas y paneles en Lua, Luau y Roblox Studio. Un core portable, una API coherente y movimiento con intención.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#docs" className="group inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Empezar ahora <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></a><a href="https://github.com/donniehuamani-max/dereus-luau" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/12 bg-white/[.04] px-5 py-3 text-sm font-medium"><GitBranch className="size-4" /> Ver repositorio</a></div></motion.div><div className="mt-16 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><b className="text-3xl">2.7.0</b><p className="mt-1 text-xs text-white/40">current release</p></div><div className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><b className="text-3xl">Lua + Luau</b><p className="mt-1 text-xs text-white/40">portable by design</p></div><div className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><b className="text-3xl">0 deps</b><p className="mt-1 text-xs text-white/40">core runtime</p></div></div></section>
    <section id="modules" className="mx-auto max-w-7xl scroll-mt-10 px-5 py-20 lg:px-8"><div className="mb-10"><p className="mb-3 text-xs uppercase tracking-[.25em] text-primary">One library, many surfaces</p><h2 className="font-display text-4xl tracking-[-.04em] sm:text-5xl">Everything you need<br /><span className="text-white/40">to build the interface.</span></h2></div><div className="grid gap-3 md:grid-cols-2">{modules.map(({ name, description, icon: Icon, color }, i) => <motion.article key={name} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .07 }} className="group rounded-3xl border border-white/10 bg-white/[.04] p-6 transition-[border-color,background-color,transform,box-shadow] duration-500 hover:-translate-y-1 hover:border-primary/30 hover:bg-white/[.065] hover:shadow-[0_20px_60px_-30px_oklch(0.87_0.2_128/.45)]"><div className="mb-12 grid size-11 place-items-center rounded-2xl bg-white/[.06] "><Icon className={`size-5 ${color}`} /></div><h3 className="text-xl font-medium">{name}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-white/45">{description}</p><ChevronRight className="mt-5 size-4 text-primary opacity-0 transition-opacity group-hover:opacity-100" /></motion.article>)}</div></section>
    <section id="docs" className="mx-auto max-w-7xl scroll-mt-10 px-5 py-20 lg:px-8"><div className="mb-10"><p className="mb-3 text-xs uppercase tracking-[.25em] text-primary">Documentation</p><h2 className="font-display text-4xl tracking-[-.04em] sm:text-5xl">Build with clarity.</h2></div><div className="grid gap-8 lg:grid-cols-[220px_1fr]"><aside className="flex gap-2 overflow-x-auto lg:grid lg:content-start">{docs.map(doc => <button key={doc} onClick={() => setActiveDoc(doc)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-left text-sm ${activeDoc === doc ? "bg-primary font-semibold text-primary-foreground" : "text-white/45 hover:bg-white/[.06]"}`}>{doc}</button>)}</aside><div className="min-h-[280px] rounded-3xl border border-white/10 bg-white/[.035] p-6 sm:p-9"><AnimatePresence mode="wait"><motion.div key={activeDoc} initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -10 }} transition={{ duration: .25 }}><h3 className="text-2xl font-medium">{activeDoc === "Overview" ? "Una capa de UI, no un framework." : activeDoc}</h3><p className="mt-4 max-w-2xl text-sm leading-7 text-white/50">{activeDoc === "Overview" && "Dereus Library mantiene el runtime pequeño y las decisiones explícitas. El core portable maneja lifecycle y utilidades; el adaptador Luau añade Instances, ventanas y controles."}{activeDoc === "Installation" && "Añade el módulo src a tu proyecto. En Roblox Studio puedes usarlo como ModuleScript; en Lua importa el core portable sin depender del entorno Roblox."}{activeDoc === "API surface" && "Dereus.new, Window.new, AddTab, Button, Toggle, Slider, Notify y Destroy forman la superficie principal. Todas las conexiones se registran para cleanup."}{activeDoc === "Compatibility" && "Lua 5.1–5.4, LuaJIT, Luau y Roblox Studio: el core compartido conserva la misma filosofía de composición, cleanup y compatibilidad entre hosts autorizados."}</p>{activeDoc === "Compatibility" && <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/[.05] p-4"><b>Lua</b><p className="mt-1 text-xs text-white/40">5.1 · 5.2 · 5.3</p></div><div className="rounded-2xl bg-white/[.05] p-4"><b>Luau</b><p className="mt-1 text-xs text-white/40">Core + types</p></div><div className="rounded-2xl bg-white/[.05] p-4"><b>Roblox</b><p className="mt-1 text-xs text-white/40">Studio ready</p></div></div>}</motion.div></AnimatePresence></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-8 overflow-hidden rounded-[2rem] border border-primary/20 bg-primary/[.07] p-6 sm:p-10 lg:grid-cols-[.8fr_1.2fr] lg:p-14"><div><p className="mb-3 text-xs uppercase tracking-[.25em] text-primary">Start in minutes</p><h2 className="font-display text-4xl tracking-[-.04em]">A clean start<br /><span className="text-white/40">for complex tools.</span></h2><p className="mt-5 max-w-md text-sm leading-6 text-white/50">Instala el módulo, crea una instancia aislada y compón tu interfaz. El cleanup está integrado desde el primer día.</p></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-[#080a0e]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div className="flex gap-1.5"><i className="size-2 rounded-full bg-red-400/70" /><i className="size-2 rounded-full bg-amber-300/70" /><i className="size-2 rounded-full bg-primary/70" /></div><button onClick={copy} className="flex items-center gap-1.5 text-xs text-white/45 hover:text-primary">{copied ? <Check className="size-3.5 text-primary" /> : <Clipboard className="size-3.5" />}{copied ? "Copiado" : "Copiar"}</button></div><pre className="overflow-x-auto p-5 text-sm leading-7 text-white/70"><code>{install}</code></pre></div></div></section>
    <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-10 text-sm text-white/40 sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>Dereus Library es independiente de <a href="/" className="text-primary hover:underline">Dereus UI</a>. Este sitio usa Dereus UI como sistema visual.</p><a href="https://github.com/donniehuamani-max/dereus-luau" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-white/70 hover:text-primary"><Terminal className="size-4" /> Open source on GitHub</a></div></footer>
  </main>
}
